name: 10 golang build -- CI/CD pipeline

on:
  push:
    branches:
      - ci-cd
      - main
  pull_request:
    branches:
      - ci-cd
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
      issues: write
      checks: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build
        run: go build -v cmd/server/main.go
#      - name: Test
#        run: go test -v

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: server
            path: cmd/server/main.go


