name: SAST scan


on:
  workflow_run:
    workflows: ["main", "Docker Build and Push"]
    types:
        - completed
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
            QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        projectBaseDir: ./

  SonarcloudScan:
    name: SonarCloudScan1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./
